#A Program for quickly determening if an item is needed to be found in raid for a quest.

#importing the GUI library
from tkinter import *
from Itemclass import Lootinfo

#Creating the list of loot items
loot = ["Paracord", "Corrugated hose", "Malboro cigarettes", "Wilston cigarettes", "Strike cigarettes", "Horse figurine", "Cat figurine", "Bronze Lion", 
        "Gas analyzer", "Military COFDM wireless signal transmitter", "Uhf RFID reader", "VPX flash storage module", "Virtex programmable processor", 
        "Capacitors", "Wires", "Wd-40 100ml", "Car battery", "Spark plug", "Broken gphone", "CPU fan", "PC CPU", "Printed circuit board", "Graphics card", 
        "Powercord", "T-Shaped plug", "Antique vase", "Antique teapot", "Silver badge", "Clin wiper", "Portable defibrillator", "Medical bloodset", "Ox bleach", 
        "5l propane tank", "Fuel Conditioner", "Heat-exchange alkali surface washer", "Rechargeable battery", "Secure flash drive", "42nd signature blend english tea", 
        "Golden rooster", "Roler submariner gold wrist watch", "Battered antique book", "Fireklean gun lube", "Old firesteel", "Deadlyslob's beard oil", "Golden 1gphone", 
        "6-sten-140-m military battery", "Ofz 30x160mm shell", "KEKtape duct tape", "Raven figurine", "Ripstop cloth", "Aramid fiber cloth", "Fleece cloth", 
        "Polyamide fabric Cordura", "Can of dr. lupo's coffee beans", "Veritas guitar pick" ]

#creating loot objects from Lootinfo class
Paracord = Lootinfo(TRUE, "3", "0", "0", 0)
Corrugated_Hose = Lootinfo(TRUE, "2", "2", "26", 0)
Malboro_cigarettes = Lootinfo(TRUE, "5", "0", "0", 0)
Wilston_cigarettes = Lootinfo(TRUE, "5", "0", "0", 0)
Strike_cigarettes = Lootinfo(TRUE, "5", "0", "0", 0)
Horse_figurine = Lootinfo(TRUE, "2", "0", "0", 0)
Cat_figurine = Lootinfo(TRUE, "1", "0", "0", 0)
Bronze_Lion = Lootinfo(TRUE, "2", "0", "4", 0)
Gas_analyzer = Lootinfo(TRUE, "2", "0", "3", "1")
Military_COFDM_wireless_signal_transmitter = Lootinfo(TRUE, "1", "0", "2", 0)
Uhf_RFID_reader = Lootinfo(TRUE, "1", "0", "0", 0)
VPX_flash_storage_module = Lootinfo(TRUE, "1", "0", "2", 0)
Virtex_programmable_processor = Lootinfo(TRUE, "2", "0", "0", 0)
Capacitors = Lootinfo(TRUE, "5", "0", "12", 0)
Wires = Lootinfo(TRUE, "5", "0", "53", 0)
Wd40_100ml = Lootinfo(TRUE, "1", "0", "4", 0)
Car_battery = Lootinfo(TRUE, "4", "0", "5", 0)
Spark_plug = Lootinfo(TRUE, "8", "0", "5", 0)
Broken_gphone = Lootinfo(TRUE, "3", "0", "0", 0)
CPU_fan = Lootinfo(TRUE, "8", "0", "50", 0)
PC_CPU = Lootinfo(TRUE, "3", "0", "0", 0)
Printed_circuit_board = Lootinfo(TRUE, "2", "3", "10", 0)
Graphics_card = Lootinfo(TRUE, "3", "0", "0", 0)
Powercord = Lootinfo(TRUE, "2", "0", "13", 0)
TShaped_plug = Lootinfo(TRUE, "4", "0", "0", 0)
Antique_vase = Lootinfo(TRUE, "2", "0", "0", 0)
Antique_teapot = Lootinfo(TRUE, "3", "0", "0", 0)
Silver_badge = Lootinfo(TRUE, "1", "0", "0", 0)
Clin_wiper = Lootinfo(TRUE, "2", "0", "0", 0)
Portable_defibrillator = Lootinfo(TRUE, "1", "0", "0", 0)
Medical_bloodset = Lootinfo(TRUE, "3", "0", "2", 0)
Ox_bleach = Lootinfo(TRUE, "3", "0", "0", 0)
Fivel_propane_tank = Lootinfo(TRUE, "2", "0", "0", 0)
Fuel_Conditioner = Lootinfo(TRUE, "4", "0", "0", 0)
Heat_exchange_alkali_surface_washer = Lootinfo(TRUE, "2", "0", "2", 0)
Rechargeable_battery = Lootinfo(TRUE, "3", "0", "0", 0)
Secure_flash_drive = Lootinfo(TRUE, "2", "3", "3", 0)
Fortysecond_signature_blend_english_tea = Lootinfo(TRUE, "1", "0", "0", 0)
Golden_rooster = Lootinfo(TRUE, "1", "0", "0", 0)
Roler_submariner_gold_wrist_watch = Lootinfo(TRUE, "1", "0", "4", 0)
Battered_antique_book = Lootinfo(TRUE, "1", "0", "0", 0)
Fireklean_gun_lube = Lootinfo(TRUE, "1", "0", "1", 0)
Old_firesteel = Lootinfo(TRUE, "1", "0", "0", 0)
Deadlyslobs_beard_oil = Lootinfo(TRUE, "1", "0", "0", 0)
Golden_1gphone = Lootinfo(TRUE, "1", "0", "0", "1")
sixsten140m_military_battery = Lootinfo(TRUE, "1", "0", "0", 0)
Ofz_30x160mm_shell = Lootinfo(TRUE, "10", "0", "0", 0)
KEKtape_duct_tape = Lootinfo(TRUE, "5", "0", "0", 0)
Raven_figurine = Lootinfo(TRUE, "1", "0", "0", 0)
Ripstop_cloth = Lootinfo(TRUE, "10", "0", "0", 0)
Aramid_fiber_cloth = Lootinfo(TRUE, "5", "0", "0", 0)
Fleece_cloth = Lootinfo(TRUE, "10", "0", "0", 0)
Polyamide_fabric_Cordura = Lootinfo(TRUE, "10", "0", "0", 0)
Can_of_dr_lupos_coffee_beans = Lootinfo(TRUE, "1", "0", "0", 0)
Veritas_guitar_pick = Lootinfo(TRUE, "1", "0", "0", 0)

root = Tk()
root.title('List of Items That Need Found in Raid Status')

# Creating a Frame for the listed items
mainFrame = LabelFrame(root)
mainFrame.grid(row=0, column=0, columnspan=2, padx = 5, pady = 5)

#function for displaying how many Found in raid items you need for the first quest
def newwindow(listitem):
    howmanyitems = Label(mainFrame, text=listitem.quest1, width=35)
    howmanyitems.grid(row=27, column=1)


# Creating a Button Widget for each loot item
#while x<len(loot)-1:
   # evenList = Button(mainFrame, text=loot[x], width=35)
   # evenList.grid(row=x, column=0)
   # x=x+1
   # oddList = Button(mainFrame, text=loot[x], width=35)
   # oddList.grid(row=x-1, column=1)
   # x=x+1

#Button widgets for each loot item
Paracordbutton = Button(mainFrame, text="Paracord", width=35, padx=5, command=lambda:newwindow(Paracord))
Corrugated_Hosebutton = Button(mainFrame, text="Corrugated Hose", width=35, padx=5, command=lambda:newwindow(Corrugated_Hose))
Malboro_cigarettesbutton = Button(mainFrame, text="Malboro cigarettes", width=35, padx=5, command=lambda:newwindow(Malboro_cigarettes))
Wilston_cigarettesbutton = Button(mainFrame, text="Wilston cigarettes", width=35, padx=5, command=lambda:newwindow(Wilston_cigarettes))
Strike_cigarettesbutton = Button(mainFrame, text="Strike cigarettes", width=35, padx=5, command=lambda:newwindow(Strike_cigarettes))
Horse_figurinebutton = Button(mainFrame, text="Horse figurine", width=35, padx=5, command=lambda:newwindow(Horse_figurine))
Cat_figurinebutton = Button(mainFrame, text="Cat figurine", width=35, padx=5, command=lambda:newwindow(Cat_figurine))
Bronze_Lionbutton = Button(mainFrame, text="Bronze Lion", width=35, padx=5, command=lambda:newwindow(Bronze_Lion))
Gas_analyzerbutton = Button(mainFrame, text="Gas analyzer", width=35, padx=5, command=lambda:newwindow(Gas_analyzer))
Military_COFDM_wireless_signal_transmitterbutton = Button(mainFrame, text="Military COFDM wireless signal transmitter", width=35, padx=5, command=lambda:newwindow(Military_COFDM_wireless_signal_transmitter))
Uhf_RFID_readerbutton = Button(mainFrame, text="Uhf RFID reader", width=35, padx=5, command=lambda:newwindow(Uhf_RFID_reader))
VPX_flash_storage_modulebutton = Button(mainFrame, text="VPX flash storage module", width=35, padx=5, command=lambda:newwindow(VPX_flash_storage_module))
Virtex_programmable_processorbutton = Button(mainFrame, text="Virtex programmable processor", width=35, padx=5, command=lambda:newwindow(Virtex_programmable_processor))
Capacitorsbutton = Button(mainFrame, text="Capacitors", width=35, padx=5, command=lambda:newwindow(Capacitors))
Wiresbutton = Button(mainFrame, text="Wires", width=35, padx=5, command=lambda:newwindow(Wires))
Wd40_100mlbutton = Button(mainFrame, text="Wd-40 100ml", width=35, padx=5, command=lambda:newwindow(Wd40_100ml))
Car_batterybutton = Button(mainFrame, text="Car battery", width=35, padx=5, command=lambda:newwindow(Car_battery))
Spark_plugbutton = Button(mainFrame, text="Spark plug", width=35, padx=5, command=lambda:newwindow(Spark_plug))
Broken_gphonebutton = Button(mainFrame, text="Broken gphone", width=35, padx=5, command=lambda:newwindow(Broken_gphone))
CPU_fanbutton = Button(mainFrame, text="CPU fan", width=35, padx=5, command=lambda:newwindow(CPU_fan))
PC_CPUbutton = Button(mainFrame, text="PC CPU", width=35, padx=5, command=lambda:newwindow(PC_CPU))
Printed_circuit_boardbutton = Button(mainFrame, text="Printed circuit board", width=35, padx=5, command=lambda:newwindow(Printed_circuit_board))
Graphics_cardbutton = Button(mainFrame, text="Graphics card", width=35, padx=5, command=lambda:newwindow(Graphics_card))
Powercordbutton = Button(mainFrame, text="Powercord", width=35, padx=5, command=lambda:newwindow(Powercord))
TShaped_plugbutton = Button(mainFrame, text="T-Shaped plug", width=35, padx=5, command=lambda:newwindow(TShaped_plug))
Antique_vasebutton = Button(mainFrame, text="Antique vase", width=35, padx=5, command=lambda:newwindow(Antique_vase))
Antique_teapotbutton = Button(mainFrame, text="Antique teapot", width=35, padx=5, command=lambda:newwindow(Antique_teapot))
Silver_badgebutton = Button(mainFrame, text="Silver badge", width=35, padx=5, command=lambda:newwindow(Silver_badge))
Clin_wiperbutton = Button(mainFrame, text="Clin wiper", width=35, padx=5, command=lambda:newwindow(Clin_wiper))
Portable_defibrillatorbutton = Button(mainFrame, text="Portable defibrillator", width=35, padx=5, command=lambda:newwindow(Portable_defibrillator))
Medical_bloodsetbutton = Button(mainFrame, text="Medical bloodset", width=35, padx=5, command=lambda:newwindow(Medical_bloodset))
Ox_bleachbutton = Button(mainFrame, text="Ox bleach", width=35, padx=5, command=lambda:newwindow(Ox_bleach))
Fivel_propane_tankbutton = Button(mainFrame, text="5l propane tank", width=35, padx=5, command=lambda:newwindow(Fivel_propane_tank))
Fuel_Conditionerbutton = Button(mainFrame, text="Fuel Conditioner", width=35, padx=5, command=lambda:newwindow(Fuel_Conditioner))
Heat_exchange_alkali_surface_washerbutton = Button(mainFrame, text="Heat-exchange alkali surface washer", width=35, padx=5, command=lambda:newwindow(Heat_exchange_alkali_surface_washer))
Rechargeable_batterybutton = Button(mainFrame, text="Rechargeable battery", width=35, padx=5, command=lambda:newwindow(Rechargeable_battery))
Secure_flash_drivebutton = Button(mainFrame, text="Secure flash drive", width=35, padx=5, command=lambda:newwindow(Secure_flash_drive))
Fortysecond_signature_blend_english_teabutton = Button(mainFrame, text="42nd signature blend english tea", width=35, padx=5, command=lambda:newwindow(Fortysecond_signature_blend_english_tea))
Golden_roosterbutton = Button(mainFrame, text="Golden rooster", width=35, padx=5, command=lambda:newwindow(Golden_rooster))
Roler_submariner_gold_wrist_watchbutton = Button(mainFrame, text="Roler submariner gold wrist watch", width=35, padx=5, command=lambda:newwindow(Roler_submariner_gold_wrist_watch))
Battered_antique_bookbutton = Button(mainFrame, text="Battered antique book", width=35, padx=5, command=lambda:newwindow(Battered_antique_book))
Fireklean_gun_lubebutton = Button(mainFrame, text="Fireklean gun lube", width=35, padx=5, command=lambda:newwindow(Fireklean_gun_lube))
Old_firesteelbutton = Button(mainFrame, text="Old firesteel", width=35, padx=5, command=lambda:newwindow(Old_firesteel))
Deadlyslobs_beard_oilbutton = Button(mainFrame, text="Deadlyslob's beard oil", width=35, padx=5, command=lambda:newwindow(Deadlyslobs_beard_oil))
Golden_1gphonebutton = Button(mainFrame, text="Golden 1gphone", width=35, padx=5, command=lambda:newwindow(Golden_1gphone))
sixsten140m_military_batterybutton = Button(mainFrame, text="6-sten-140-m military battery", width=35, padx=5, command=lambda:newwindow(sixsten140m_military_battery))
Ofz_30x160mm_shellbutton = Button(mainFrame, text="Ofz 30x160mm shell", width=35, padx=5, command=lambda:newwindow(Ofz_30x160mm_shell))
KEKtape_duct_tapebutton = Button(mainFrame, text="KEKtape duct tape", width=35, padx=5, command=lambda:newwindow(KEKtape_duct_tape))
Raven_figurinebutton = Button(mainFrame, text="Raven figurine", width=35, padx=5, command=lambda:newwindow(Raven_figurine))
Ripstop_clothbutton = Button(mainFrame, text="Ripstop cloth", width=35, padx=5, command=lambda:newwindow(Ripstop_cloth))
Aramid_fiber_clothbutton = Button(mainFrame, text="Aramid fiber cloth", width=35, padx=5, command=lambda:newwindow(Aramid_fiber_cloth))
Fleece_clothbutton = Button(mainFrame, text="Fleece cloth", width=35, padx=5, command=lambda:newwindow(Fleece_cloth))
Polyamide_fabric_Cordurabutton = Button(mainFrame, text="Polyamide fabric Cordura", width=35, padx=5, command=lambda:newwindow(Polyamide_fabric_Cordura))
Can_of_dr_lupos_coffee_beansbutton = Button(mainFrame, text="Can of dr. lupo's coffee beans", width=35, padx=5, command=lambda:newwindow(Can_of_dr_lupos_coffee_beans))
Veritas_guitar_pickbutton = Button(mainFrame, text="Veritas guitar pick", width=35, padx=5, command=lambda:newwindow(Veritas_guitar_pick))

#grid positions for each button widget
Paracordbutton.grid(row=0, column=0)
Corrugated_Hosebutton.grid(row=0, column=1)
Malboro_cigarettesbutton.grid(row=1, column=0)
Wilston_cigarettesbutton.grid(row=1, column=1)
Strike_cigarettesbutton.grid(row=2, column=0)
Horse_figurinebutton.grid(row=2, column=1)
Cat_figurinebutton.grid(row=3, column=0)
Bronze_Lionbutton.grid(row=3, column=1)
Gas_analyzerbutton.grid(row=4, column=0)
Military_COFDM_wireless_signal_transmitterbutton.grid(row=4, column=1)
Uhf_RFID_readerbutton.grid(row=5, column=0)
VPX_flash_storage_modulebutton.grid(row=5, column=1)
Virtex_programmable_processorbutton.grid(row=6, column=0)
Capacitorsbutton.grid(row=6, column=1)
Wiresbutton.grid(row=7, column=0)
Wd40_100mlbutton.grid(row=7, column=1)
Car_batterybutton.grid(row=8, column=0)
Spark_plugbutton.grid(row=8, column=1)
Broken_gphonebutton.grid(row=9, column=0)
CPU_fanbutton.grid(row=9, column=1)
PC_CPUbutton.grid(row=10, column=0)
Printed_circuit_boardbutton.grid(row=10, column=1)
Graphics_cardbutton.grid(row=11, column=0)
Powercordbutton.grid(row=11, column=1)
TShaped_plugbutton.grid(row=12, column=0)
Antique_vasebutton.grid(row=12, column=1)
Antique_teapotbutton.grid(row=13, column=0)
Silver_badgebutton.grid(row=13, column=1)
Clin_wiperbutton.grid(row=14, column=0)
Portable_defibrillatorbutton.grid(row=14, column=1)
Medical_bloodsetbutton.grid(row=15, column=0)
Ox_bleachbutton.grid(row=15, column=1)
Fivel_propane_tankbutton.grid(row=16, column=0)
Fuel_Conditionerbutton.grid(row=16, column=1)
Heat_exchange_alkali_surface_washerbutton.grid(row=17, column=0)
Rechargeable_batterybutton.grid(row=17, column=1)
Secure_flash_drivebutton.grid(row=18, column=0)
Fortysecond_signature_blend_english_teabutton.grid(row=18, column=1)
Golden_roosterbutton.grid(row=19, column=0)
Roler_submariner_gold_wrist_watchbutton.grid(row=19, column=1)
Battered_antique_bookbutton.grid(row=20, column=0)
Fireklean_gun_lubebutton.grid(row=20, column=1)
Old_firesteelbutton.grid(row=21, column=0)
Deadlyslobs_beard_oilbutton.grid(row=21, column=1)
Golden_1gphonebutton.grid(row=22, column=0)
sixsten140m_military_batterybutton.grid(row=22, column=1)
Ofz_30x160mm_shellbutton.grid(row=23, column=0)
KEKtape_duct_tapebutton.grid(row=23, column=1)
Raven_figurinebutton.grid(row=24, column=0)
Ripstop_clothbutton.grid(row=24, column=1)
Aramid_fiber_clothbutton.grid(row=25, column=0)
Fleece_clothbutton.grid(row=25, column=1)
Polyamide_fabric_Cordurabutton.grid(row=26, column=0)
Can_of_dr_lupos_coffee_beansbutton.grid(row=26, column=1)
Veritas_guitar_pickbutton.grid(row=27, column=0)

#Creating the main loop
root.mainloop()
